print("A")
liczba = int(3 - 2 + 1)
print(liczba)
print("B")
liczba = int(5 + 10 * 5)
print(liczba)
print("C")
liczba = int(4 + 4 / 2 ** 2)
print(liczba)
print("D")
liczba = int(4 % 3 % 2 % 1)
print(liczba)
print("E")
liczba = int(1 + 2 % 3 ** 4 * 5)
print(liczba)
print("F")
liczba = int(True != False)
print(liczba)