print("A")
liczba = int(5 + 10 * 5)
print(liczba)
print("B")
liczba = int(3 - 2 + 1)
print(liczba)
print("C")
liczba = int(2 + -3)
print(liczba)
print("D")
liczba = int(2 ** 8)
print(liczba)
print("E")
liczba = int(4 + 4 / 2 ** 2)
print(liczba)
print("F")
liczba = int(4 % 3 % 2 % 1 )
print(liczba)
print("G")
liczba = int(1 + 2 % 3 ** 4 * 5)
print(liczba)
print("H")
liczba = int(True != False)
print(liczba)
print("I")
liczba = int(2 <= 3 or False)
print(liczba)
print("J")
liczba = int(not True or not False and not True)
print(liczba)
print("K")
liczba = int(2 < 3 and 4 < 5 or not 6 < 7)
print(liczba)
print("L")
liczba = int(2 % 3 < 4 / 5 and 6 + 7 < 8 or not 9 + 10 == 19)
print(liczba)
print("M")
liczba = int(0b11111 >> 1 >> 1 >> 1)
print(liczba)
print("N")
liczba = int(0x11 + 0b11 + 11)
print(liczba)
print("O")
liczba = int(2 << 3 >> 4)
print(liczba)

