print("A")
liczba = int(15*38)
print(liczba)
print("B")
liczba = int(3 + 4)
liczba2 = int(5 + 9)
print(liczba)
print(liczba2)
print("C")
liczba = int(7/2)
print(liczba)
print("D")
liczba = int(48%5)
print(liczba)
print("E")
liczba = int(8+7+4+2/4)
print(liczba)
print("F")
liczba = int(2**10)
print(liczba)
print("G")
liczba = int(49**(1.5))
print(liczba)
print("H")
liczba = int(80*0.25)
print(liczba)

